"""Add bulk upload fields

Revision ID: 21b35e134658
Revises: 3d5f8694d988
Create Date: 2026-02-19 21:35:35.581618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b35e134658'
down_revision: Union[str, None] = '3d5f8694d988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('order_date', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('item_code', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('item_name', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('coo', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('ref_no', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('doc_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'doc_status')
    op.drop_column('shipments', 'ref_no')
    op.drop_column('shipments', 'buyer_name')
    op.drop_column('shipments', 'brand')
    op.drop_column('shipments', 'coo')
    op.drop_column('shipments', 'item_name')
    op.drop_column('shipments', 'item_code')
    op.drop_column('shipments', 'order_date')
    # ### end Alembic commands ###
