"""rename estimated_eta to final_destination_eta

Revision ID: 3d5f8694d988
Revises: 05a6b39d1356
Create Date: 2026-02-15 15:54:09.945523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5f8694d988'
down_revision: Union[str, None] = '05a6b39d1356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('final_destination_eta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'final_destination_eta')
    # ### end Alembic commands ###
