"""add_is_email_verified_to_users

Revision ID: 45ed6e62befc
Revises: e11753b483fd
Create Date: 2026-02-11 19:51:46.286249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ed6e62befc'
down_revision: Union[str, None] = 'e11753b483fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('last_location', sa.String(), nullable=True),
    sa.Column('last_location_terminal', sa.String(), nullable=True),
    sa.Column('next_location', sa.String(), nullable=True),
    sa.Column('next_location_terminal', sa.String(), nullable=True),
    sa.Column('current_vessel_name', sa.String(), nullable=True),
    sa.Column('current_voyage_number', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_movement_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_history_id'), 'shipment_history', ['id'], unique=False)
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_verified')
    op.drop_index(op.f('ix_shipment_history_id'), table_name='shipment_history')
    op.drop_table('shipment_history')
    # ### end Alembic commands ###
