"""add vessel info to shipment history

Revision ID: 58b0b6974866
Revises: a0934fdf0582
Create Date: 2026-02-15 07:00:01.369259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b0b6974866'
down_revision: Union[str, None] = 'a0934fdf0582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_history', sa.Column('vessel_lat', sa.Float(), nullable=True))
    op.add_column('shipment_history', sa.Column('vessel_lon', sa.Float(), nullable=True))
    op.add_column('shipment_history', sa.Column('vessel_speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_history', 'vessel_speed')
    op.drop_column('shipment_history', 'vessel_lon')
    op.drop_column('shipment_history', 'vessel_lat')
    # ### end Alembic commands ###
