"""add final destination columns

Revision ID: 80cb497246c0
Revises: 58b0b6974866
Create Date: 2026-02-15 15:41:56.874731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cb497246c0'
down_revision: Union[str, None] = '58b0b6974866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('final_destination', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('final_destination_port', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'final_destination_port')
    op.drop_column('shipments', 'final_destination')
    # ### end Alembic commands ###
