"""newchanges

Revision ID: a0934fdf0582
Revises: 4e6ed06fbd7c
Create Date: 2026-02-12 22:45:20.760253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0934fdf0582'
down_revision: Union[str, None] = '4e6ed06fbd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('shipments', sa.Column('ata_final_destination', sa.DateTime(), nullable=True))
    op.add_column('shipments', sa.Column('vessel_lat', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('vessel_lon', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('vessel_speed', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('vessel_course', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('shipments', sa.Column('co2_emissions', sa.Float(), nullable=True))
    op.create_index(op.f('ix_shipments_share_token'), 'shipments', ['share_token'], unique=True)
    op.add_column('users', sa.Column('notify_on_arrival', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_on_departure', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_on_delay', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_via_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_via_whatsapp', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'whatsapp_number')
    op.drop_column('users', 'notify_via_whatsapp')
    op.drop_column('users', 'notify_via_email')
    op.drop_column('users', 'notify_on_delay')
    op.drop_column('users', 'notify_on_departure')
    op.drop_column('users', 'notify_on_arrival')
    op.drop_index(op.f('ix_shipments_share_token'), table_name='shipments')
    op.drop_column('shipments', 'co2_emissions')
    op.drop_column('shipments', 'is_public')
    op.drop_column('shipments', 'share_token')
    op.drop_column('shipments', 'vessel_course')
    op.drop_column('shipments', 'vessel_speed')
    op.drop_column('shipments', 'vessel_lon')
    op.drop_column('shipments', 'vessel_lat')
    op.drop_column('shipments', 'ata_final_destination')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
