"""update_shipment_table

Revision ID: e11753b483fd
Revises: 1a2b3c4d5e6f
Create Date: 2026-01-30 11:49:04.723629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11753b483fd'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=True),
    sa.Column('container_status', sa.String(), nullable=True),
    sa.Column('shipping_line_name', sa.String(), nullable=True),
    sa.Column('shipping_line_id', sa.String(), nullable=True),
    sa.Column('tare', sa.String(), nullable=True),
    sa.Column('shipped_from', sa.String(), nullable=True),
    sa.Column('shipped_from_terminal', sa.String(), nullable=True),
    sa.Column('shipped_to', sa.String(), nullable=True),
    sa.Column('shipped_to_terminal', sa.String(), nullable=True),
    sa.Column('atd_origin', sa.DateTime(), nullable=True),
    sa.Column('eta_final_destination', sa.DateTime(), nullable=True),
    sa.Column('last_location', sa.String(), nullable=True),
    sa.Column('last_location_terminal', sa.String(), nullable=True),
    sa.Column('next_location', sa.String(), nullable=True),
    sa.Column('next_location_terminal', sa.String(), nullable=True),
    sa.Column('atd_last_location', sa.DateTime(), nullable=True),
    sa.Column('eta_next_destination', sa.DateTime(), nullable=True),
    sa.Column('timestamp_of_last_location', sa.DateTime(), nullable=True),
    sa.Column('last_movement_timestamp', sa.DateTime(), nullable=True),
    sa.Column('loading_port', sa.String(), nullable=True),
    sa.Column('discharging_port', sa.String(), nullable=True),
    sa.Column('last_vessel_name', sa.String(), nullable=True),
    sa.Column('last_voyage_number', sa.String(), nullable=True),
    sa.Column('current_vessel_name', sa.String(), nullable=True),
    sa.Column('current_voyage_number', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_container_id'), 'shipments', ['container_id'], unique=False)
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_container_id'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
